@startuml
package com.iluwatar.tls {
  class App {
    - LOGGER : Logger {static}
    + App()
    + main(args : String[]) {static}
    - makeServiceCalls(service : B2BService) {static}
  }
  ~class B2BService {
    - LOGGER : Logger {static}
    - callsCounter : int
    - tenant : Tenant
    + B2BService(tenant : Tenant)
    + dummyCustomerApi() : int
    + getCurrentCallsCount() : int
    - getRandomCustomerId() : int
  }
  class Tenant {
    - allowedCallsPerSecond : int
    - name : String
    + Tenant(name : String, allowedCallsPerSecond : int)
    + getAllowedCallsPerSecond() : int
    + getName() : String
    + setAllowedCallsPerSecond(allowedCallsPerSecond : int)
    + setName(name : String)
  }
}
B2BService -->  "-tenant" Tenant
@enduml