@startuml
package com.iluwatar.datamapper {
  class App {
    - STUDENT_STRING : String {static}
    - log : Logger {static}
    - App()
    + main(args : String[]) {static}
  }
  class domain.Student {
    - grade : char
    - name : String
    - serialVersionUID : long {static}
    - studentId : int
    + domain.Student(studentId : int, name : String, grade : char)
    + equals(inputObject : Object) : boolean
    + getGrade() : char
    + getName() : String
    + getStudentId() : int
    + hashCode() : int
    + setGrade(grade : char)
    + setName(name : String)
    + setStudentId(studentId : int)
    + toString() : String
  }
  interface StudentDataMapper {
    + delete(domain.Student) {abstract}
    + find(int) : Optional<domain.Student> {abstract}
    + insert(domain.Student) {abstract}
    + update(domain.Student) {abstract}
  }
  class StudentDataMapperImpl {
    - students : List<domain.Student>
    + StudentDataMapperImpl()
    + delete(studentToBeDeleted : domain.Student)
    + find(studentId : int) : Optional<domain.Student>
    + getStudents() : List<domain.Student>
    + insert(studentToBeInserted : domain.Student)
    + update(studentToBeUpdated : domain.Student)
  }
}
StudentDataMapperImpl -->  "-students" domain.Student
StudentDataMapperImpl ..|> StudentDataMapper 
@enduml
