@startuml
package com.iluwatar.remotefacade.assemblersfacades {
  class Customerdtoassembler {
    + Customerdtoassembler()
    + makeCustomer(dataObject : Customerdto) {static}
    + makeCustomerdto(cstmr : Customer) : Customerdto {static}
  }
  class RemoteFacade {
    + RemoteFacade()
    + makeClient(dataObject : Customerdto) {static}
  }
}
package com.iluwatar.remotefacade {
  class Client {
    - LOGGER : Logger {static}
    + Client()
    + main(args : String[]) {static}
    - printCustomerDetails(list : List<Customer>) {static}
  }
}
package com.iluwatar.remotefacade.dto {
  class Customerdto {
    + address : String
    + name : String
    + phone : String
    + Customerdto()
  }
}
package com.iluwatar.remotefacade.domain {
  class Customer {
    - address : String
    - name : String
    - phone : String
    + Customer(customername : String, customerphone : String, customeradress : String)
    + getAddress() : String
    + getName() : String
    + getPhone() : String
  }
  class Store{
    + customers : List<Customer> {static}
    + Store()
  }
}
Store -->  "-customers" Customer
Customerdtoassembler --> RemoteFacade
RemoteFacade --> Store
RemoteFacade <-- Client
Customerdto --> Customerdtoassembler

@enduml