# You can also specify the server port in the application.properties file.
# Uncomment the following line and set the desired port number to change
# the default port (8080) to a different value.
#server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Force Spring Boot to always run SQL initialization scripts on startup
spring.sql.init.mode=always

# If using Spring Data JPA / Hibernate, defer data insertion until AFTER entities are generated
spring.jpa.defer-datasource-initialization=true

# Keep Hibernate's DDL generation active (or set to 'update')
spring.jpa.hibernate.ddl-auto=create-drop
