@startuml
package com.iluwatar.queryobject {
  class App {
    - LOGGER : Logger {static}
    + main(args : String[]) {static}
  }
  class Customer {
    + name : String
    + orders : Collection<CustomerOrder>
  }
  class CustomerOrder {
    + orderDetails : Collection<CustomerOrderDetail>
  }
  class CustomerOrderDetail {
    + quantity : double
    + unitPrice : double
  }
  class Repository<T>{
    + dbContext : Collection<T>
    + query(criteria : QueryObject<T>[]) : Collection<T>
  }

  class QueryObject<T>{
    + query() : Predicate<T>
  }
}
@enduml