@startuml
enum Rate [[java:com.callusage.application.Rate]] {
	RATE_PER_SECOND
	RATE_PER_MB
	rate
	~Rate(rate: double)
	+getRate(): double
}
class UsageCostProcessor [[java:com.callusage.application.UsageCostProcessor]] {
	~persistentCommonStorageUtility: IPersistentCommonStorageUtility
	-ratePerSecond: double
	-ratePerMB: double
	+processUsageCost(inputMessageHeader: MessageHeader): void
}

class UsageCostProcessorApplication [[java:com.callusage.application.UsageCostProcessorApplication]] {
	+{static} main(args: String[]): void
}


class "Message<T>" as Message_T_ [[java:com.callusage.domain.Message]] {
	-messageHeader: MessageHeader
	-messageData: MessageData<T>
	+Message(messageHeader: MessageHeader, messageData: MessageData<T>)
	+getMessageData(): MessageData<T>
	+getMessageHeader(): MessageHeader
	+toString(): String
}


class MessageHeader [[java:com.callusage.domain.MessageHeader]] {
	-dataLocation: String
	-dataFileName: String
	-operataionName: String
	+getDataLocation(): String
	+setDataLocation(dataLocation: String): void
	+getDataFileName(): String
	+setDataFileName(dataFileName: String): void
	+getOperataionName(): String
	+setOperataionName(operataionName: String): void
	+toString(): String
}


class "MessageData<T>" as MessageData_T_ [[java:com.callusage.domain.MessageData]] {
	-data: T
	+MessageData(data: T)
	+getData(): T
	+toString(): String
}



class UsageDetail [[java:com.callusage.domain.UsageDetail]] {
	-userId: String
	-duration: long
	-data: long
	+UsageDetail()
	+getUserId(): String
	+setUserId(userId: String): void
	+getDuration(): long
	+setDuration(duration: long): void
	+getData(): long
	+setData(data: long): void
}


class UsageCostDetail [[java:com.callusage.domain.UsageCostDetail]] {
	-userId: String
	-callCost: double
	-dataCost: double
	+UsageCostDetail()
	+getUserId(): String
	+setUserId(userId: String): void
	+getCallCost(): double
	+setCallCost(callCost: double): void
	+getDataCost(): double
	+setDataCost(dataCost: double): void
	+toString(): String
}



interface IPersistentCommonStorageUtility [[java:com.callusage.interfaces.IPersistentCommonStorageUtility]] {
	readMessageFromPersistentStorage(messageHeader: MessageHeader): Message
	dropMessageToPersistentStorage(message: Message): void
}


class PersistentLocalStorageUtility [[java:com.callusage.utility.PersistentLocalStorageUtility]] {
	+readMessageFromPersistentStorage(messageHeader: MessageHeader): Message
	+dropMessageToPersistentStorage(message: Message): void
}
interface IPersistentCommonStorageUtility {
}
IPersistentCommonStorageUtility <|.. PersistentLocalStorageUtility



Message_T_ "1" *-- "1" MessageHeader : has
Message_T_ "1" *-- "1" MessageData_T_ : has
MessageData_T_ "1" *-- "1" UsageDetail: has
MessageData_T_ "1" *-- "1" UsageCostDetail : has
UsageCostProcessor "1" *-- "1" IPersistentCommonStorageUtility : has
UsageCostProcessor - Rate : has
UsageCostProcessorApplication - UsageCostProcessor : triggers >
@enduml