package com.iluwatar.dao;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

/** Test class */
public class AppgenerateSampleCustomers000cdcfd97ef17dc542Test {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/iluwatar/dao/App.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 130 branch to line 130
   * conditional line 131 branch to line 131
   * conditional line 132 branch to line 132
   */

  @Test
  public void comiluwatardaoAppgenerateSampleCustomers000cdcfd97ef17dc542() throws Throwable {

    java.util.List<com.iluwatar.dao.Customer> retval;
    {
      /* Arrange */

      /* Act */
      retval = com.iluwatar.dao.App.generateSampleCustomers();
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertEquals(3, retval.size());
      Assert.assertNotNull(retval.get(0));
      Assert.assertEquals("Adamson", Reflector.getInstanceField(retval.get(0), "lastName"));
      Assert.assertEquals("Adam", Reflector.getInstanceField(retval.get(0), "firstName"));
      Assert.assertEquals(1, Reflector.getInstanceField(retval.get(0), "id"));
      Assert.assertNotNull(retval.get(1));
      Assert.assertEquals("Bobson", Reflector.getInstanceField(retval.get(1), "lastName"));
      Assert.assertEquals("Bob", Reflector.getInstanceField(retval.get(1), "firstName"));
      Assert.assertEquals(2, Reflector.getInstanceField(retval.get(1), "id"));
      Assert.assertNotNull(retval.get(2));
      Assert.assertEquals("Carlson", Reflector.getInstanceField(retval.get(2), "lastName"));
      Assert.assertEquals("Carl", Reflector.getInstanceField(retval.get(2), "firstName"));
      Assert.assertEquals(3, Reflector.getInstanceField(retval.get(2), "id"));
    }
  }
}
