/*
 * This project is licensed under the MIT license. Module model-view-viewmodel is using ZK framework licensed under LGPL (see lgpl-3.0.txt).
 *
 * The MIT License
 * Copyright © 2014-2022 Ilkka Seppälä
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.iluwatar.serverfragment.fragments;

import com.iluwatar.serverfragment.types.PageContext;
import lombok.extern.slf4j.Slf4j;

/**
 * Content fragment implementation for Server-Side Page Fragment Composition.
 *
 * <p>This fragment is responsible for rendering the main content area of web pages, containing
 * page-specific information and dynamic content.
 */
@Slf4j
public class ContentFragment implements Fragment {

  @Override
  public String render(PageContext context) {
    LOGGER.info("Rendering content fragment for page: {}", context.getPageId());

    var content = generateContentByPageType(context.getPageId());

    return String.format(
        """
        <main class="main-content">
          <div class="content-wrapper">
            <h2>%s</h2>
            <div class="content-body">
              %s
            </div>
          </div>
        </main>
        """,
        context.getTitle(), content);
  }

  /**
   * Generates page-specific content based on the page type.
   *
   * @param pageId the page identifier
   * @return HTML content for the specific page
   */
  private String generateContentByPageType(String pageId) {
    return switch (pageId.toLowerCase()) {
      case "home" -> """
          <p>Welcome to our Server-Side Fragment Composition demo!</p>
          <p>This page is composed of fragments from different microservices:</p>
          <ul>
            <li>Header Service - manages navigation and branding</li>
            <li>Content Service - manages main page content</li>
            <li>Footer Service - manages footer information</li>
          </ul>
          <p>Each service can be developed, deployed, and scaled independently!</p>
          """;

      case "about" -> """
          <p>About Server-Side Page Fragment Composition Pattern</p>
          <p>This architectural pattern allows teams to:</p>
          <ul>
            <li>Develop components independently</li>
            <li>Scale services based on demand</li>
            <li>Use different technologies per service</li>
            <li>Deploy services without affecting others</li>
          </ul>
          <p>The composition happens on the server side for optimal performance.</p>
          """;

      case "contact" -> """
          <p>Contact Information</p>
          <div class="contact-info">
            <p>Email: info@example.com</p>
            <p>Phone: +1 (555) 123-4567</p>
            <p>Address: 123 Design Pattern St, Architecture City, AC 12345</p>
          </div>
          <p>Each contact method is managed by our Contact Service microservice.</p>
          """;

      default -> """
          <p>Page content for: %s</p>
          <p>This content is dynamically generated by the Content Service.</p>
          """
          .formatted(pageId);
    };
  }

  @Override
  public String getType() {
    return "content";
  }

  @Override
  public int getPriority() {
    return 2; // Medium priority - rendered after header
  }

  @Override
  public boolean isCacheable() {
    return false; // Content is often dynamic and shouldn't be cached
  }
}
