@startuml
package com.iluwatar.producer.calldetails.utility {
  class PersistentLocalStorageUtility<T> {
    - LOGGER : Logger {static}
    + PersistentLocalStorageUtility<T>()
    + dropMessageToPersistentStorage(message : Message<T>)
    + readMessageFromPersistentStorage(messageHeader : MessageHeader) : Message<T>
  }
}
package com.iluwatar.producer.calldetails.application {
  class UsageDetailSender {
    - count : long {static}
    - persistentcommonStorageUtility : IPersistentCommonStorageUtility<UsageDetail>
    - source : Source
    - users : String[]
    + UsageDetailSender()
    + incrementCount() {static}
    + sendEvents()
  }
  class UsageDetailSenderApplication {
    + UsageDetailSenderApplication()
    + main(args : String[]) {static}
  }
}
package com.iluwatar.producer.calldetails.interfaces {
  interface IPersistentCommonStorageUtility<T> {
    + dropMessageToPersistentStorage(Message<T>) {abstract}
    + readMessageFromPersistentStorage(MessageHeader) : Message<T> {abstract}
  }
}
package com.iluwatar.producer.calldetails.domain {
  class Message<T> {
    - messageData : MessageData<T>
    - messageHeader : MessageHeader
    + Message<T>(messageHeader : MessageHeader, messageData : MessageData<T>)
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getMessageData() : MessageData<T>
    + getMessageHeader() : MessageHeader
    + hashCode() : int
    + setMessageData(messageData : MessageData<T>)
    + setMessageHeader(messageHeader : MessageHeader)
    + toString() : String
  }
  class MessageData<T> {
    - data : T
    + MessageData<T>(data : T)
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getData() : T
    + hashCode() : int
    + setData(data : T)
    + toString() : String
  }
  class MessageHeader {
    - dataFileName : String
    - dataLocation : String
    - operataionName : String
    + MessageHeader()
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getDataFileName() : String
    + getDataLocation() : String
    + getOperataionName() : String
    + hashCode() : int
    + setDataFileName(dataFileName : String)
    + setDataLocation(dataLocation : String)
    + setOperataionName(operataionName : String)
    + toString() : String
  }
  class UsageDetail {
    - data : long
    - duration : long
    - userId : String
    + UsageDetail()
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getData() : long
    + getDuration() : long
    + getUserId() : String
    + hashCode() : int
    + setData(data : long)
    + setDuration(duration : long)
    + setUserId(userId : String)
    + toString() : String
  }
}
Message -->  "-messageHeader" MessageHeader
Message -->  "-messageData" MessageData
UsageDetailSender -->  "-persistentcommonStorageUtility" IPersistentCommonStorageUtility
PersistentLocalStorageUtility ..|> IPersistentCommonStorageUtility 
@enduml