@startuml
package com.iluwatar.business.delegate {
  class EjbService {
    + EjbService()
    + doProcessing()
  }
  class BusinessLookup {
    - ejbService : EjbService
    - jmsService : JmsService
    + BusinessLookup()
    + getBusinessService(serviceType : ServiceType) : BusinessService
    + setEjbService(ejbService : EjbService)
    + setJmsService(jmsService : JmsService)
  }
  class App {
    + App()
    + main(args : String[]) {static}
  }
  interface BusinessService {
    + doProcessing() {abstract}
  }
  class Client {
    - businessDelegate : BusinessDelegate
    + Client(businessDelegate : BusinessDelegate)
    + doTask()
  }
  class BusinessDelegate {
    - businessService : BusinessService
    - lookupService : BusinessLookup
    - serviceType : ServiceType
    + BusinessDelegate()
    + doTask()
    + setLookupService(businessLookup : BusinessLookup)
    + setServiceType(serviceType : ServiceType)
  }
  class JmsService {
    + JmsService()
    + doProcessing()
  }
  enum ServiceType {
    + EJB {static}
    + JMS {static}
    + valueOf(name : String) : ServiceType {static}
    + values() : ServiceType[] {static}
  }
}
BusinessDelegate -->  "-serviceType" ServiceType
BusinessLookup -->  "-ejbService" EjbService
Client -->  "-businessDelegate" BusinessDelegate
BusinessDelegate -->  "-businessService" BusinessService
BusinessDelegate -->  "-lookupService" BusinessLookup
BusinessLookup -->  "-jmsService" JmsService
EjbService ..|> BusinessService 
JmsService ..|> BusinessService 
@enduml