@startuml
package com.iluwatar.balking {
  class App {
    - LOGGER : Logger {static}
    + App()
    + main(args : String[]) {static}
  }
  class WashingMachine {
    - LOGGER : Logger {static}
    - washingMachineState : WashingMachineState
    + WashingMachine()
    + endOfWashing()
    + getWashingMachineState() : WashingMachineState
    + wash()
  }
  enum WashingMachineState {
    + ENABLED {static}
    + WASHING {static}
    + valueOf(name : String) : WashingMachineState {static}
    + values() : WashingMachineState[] {static}
  }
}
WashingMachine -->  "-washingMachineState" WashingMachineState
@enduml