@startuml
package com.iluwatar.tablemodule {
  class App {
    - H2_DB_URL : String {static}
    - LOGGER : Logger {static}
    + App()
    - addRooms(roomDao : RoomDaoImpl) {static}
    - createDataSource() : DataSource {static}
    - createSchema(dataSource : DataSource) {static}
    - deleteSchema(dataSource : DataSource) {static}
    - generateSampleRooms() : List<Room> {static}
    - getRoomStatus(dao : RoomDaoImpl) {static}
    + main(args : String[]) {static}
  }
  class Room {
    - booked : boolean
    - id : int
    - price : int
    - roomType : String
    + Room(id : int, roomType : String, price : int, booked : boolean)
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getId() : int
    + getPrice() : int
    + getRoomType() : String
    + hashCode() : int
    + isBooked() : boolean
    + setBooked(booked : boolean)
    + setId(id : int)
    + setPrice(price : int)
    + setRoomType(roomType : String)
    + toString() : String
  }
  interface RoomDao {
    + add(Room) : Boolean {abstract}
    + delete(Room) : Boolean {abstract}
    + getAll() : Stream<Room> {abstract}
    + getById(int) : Optional<Room> {abstract}
    + update(Room) : Boolean {abstract}
  }
  class RoomDaoImpl {
    - LOGGER : Logger {static}
    - dataSource : DataSource
    + RoomDaoImpl(dataSource : DataSource)
    + add(room : Room) : Boolean
    - createRoom(resultSet : ResultSet) : Room
    + delete(room : Room) : Boolean
    + getAll() : Stream<Room>
    + getById(id : int) : Optional<Room>
    - getConnection() : Connection
    - mutedClose(connection : Connection, statement : PreparedStatement, resultSet : ResultSet)
    + update(room : Room) : Boolean
  }
  class RoomSchemaSql {
    + CREATE_SCHEMA_SQL : String {static}
    + DELETE_SCHEMA_SQL : String {static}
    - RoomSchemaSql()
  }
  class RoomTableModule {
    - LOGGER : Logger {static}
    - roomDao : RoomDao
    + RoomTableModule(roomDaoImpl : RoomDaoImpl)
    + bookRoom(roomNumber : int)
    + cancelRoomBooking(roomNumber : int)
  }
}
RoomTableModule -->  "-roomDao" RoomDao
RoomDaoImpl ..|> RoomDao 
@enduml