@startuml
package com.iluwatar.servicelocator {
  class ServiceLocator {
    - serviceCache : ServiceCache {static}
    - ServiceLocator()
    + getService(serviceJndiName : String) : Service {static}
  }
  class App {
    + App()
    + main(args : String[]) {static}
  }
  class ServiceImpl {
    - id : int
    - serviceName : String
    + ServiceImpl(serviceName : String)
    + execute()
    + getId() : int
    + getName() : String
  }
  class InitContext {
    + InitContext()
    + lookup(serviceName : String) : Object
  }
  class ServiceCache {
    - serviceCache : Map<String, Service>
    + ServiceCache()
    + addService(newService : Service)
    + getService(serviceName : String) : Service
  }
  interface Service {
    + execute() {abstract}
    + getId() : int {abstract}
    + getName() : String {abstract}
  }
}
ServiceLocator -->  "-serviceCache" ServiceCache
ServiceImpl ..|> Service 
@enduml