@startuml
package com.iluwatar.composite {
  class Word {
    + Word(letters : List<Letter>)
    # printThisAfter()
    # printThisBefore()
  }
  class App {
    + App()
    + main(args : String[]) {static}
  }
  class Messenger {
    + Messenger()
    ~ messageFromElves() : LetterComposite
    ~ messageFromOrcs() : LetterComposite
  }
  class Letter {
    - c : char
    + Letter(c : char)
    # printThisAfter()
    # printThisBefore()
  }
  class Sentence {
    + Sentence(words : List<Word>)
    # printThisAfter()
    # printThisBefore()
  }
  abstract class LetterComposite {
    - children : List<LetterComposite>
    + LetterComposite()
    + add(letter : LetterComposite)
    + count() : int
    + print()
    # printThisAfter() {abstract}
    # printThisBefore() {abstract}
  }
}
LetterComposite -->  "-children" LetterComposite
Word --|> LetterComposite 
Letter --|> LetterComposite 
Sentence --|> LetterComposite 
@enduml