/*
 *
 *  * This project is licensed under the MIT license. Module model-view-viewmodel is using ZK framework licensed under LGPL (see lgpl-3.0.txt).
 *  *
 *  * The MIT License
 *  * Copyright © 2014-2022 Ilkka Seppälä
 *  *
 *  * Permission is hereby granted, free of charge, to any person obtaining a copy
 *  * of this software and associated documentation files (the "Software"), to deal
 *  * in the Software without restriction, including without limitation the rights
 *  * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  * copies of the Software, and to permit persons to whom the Software is
 *  * furnished to do so, subject to the following conditions:
 *  *
 *  * The above copyright notice and this permission notice shall be included in
 *  * all copies or substantial portions of the Software.
 *  *
 *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *  * THE SOFTWARE.
 *
 */
package com.iluwatar.onion.application.usecase;

import com.iluwatar.onion.application.dto.SavePersonCommand;
import com.iluwatar.onion.domain.exception.DomainException;
import com.iluwatar.onion.domain.model.Category;
import com.iluwatar.onion.domain.model.Person;
import com.iluwatar.onion.domain.repository.PersonRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class SavePersonUseCaseTest {

    @Mock
    private PersonRepository personRepository;

    @Captor
    private ArgumentCaptor<Person> personCaptor;

    private SavePersonUseCase savePersonUseCase;

    @BeforeEach
    void setUp() {
        savePersonUseCase = new SavePersonUseCase(personRepository);
    }

    @Nested
    @DisplayName("Execute - Happy Path")
    class ExecuteHappyPath {

        @Test
        @DisplayName("Should save person and return PersonResponse")
        void shouldSavePersonAndReturnResponse() {
            // Arrange
            var command = new SavePersonCommand(
                    "John",
                    "Doe",
                    25,
                    "+1234567890",
                    "john.doe@example.com",
                    "123 Main St",
                    1L,
                    "Professional"
            );

            var category = new Category(1L, "Professional");
            var savedPerson = new Person(
                    100L, // ID generated by database
                    "John",
                    "Doe",
                    25,
                    "+1234567890",
                    "john.doe@example.com",
                    category
            );

            when(personRepository.save(any(Person.class))).thenReturn(savedPerson);

            // Act
            var response = savePersonUseCase.execute(command);

            // Assert
            assertNotNull(response);
            assertEquals(100L, response.id());
            assertEquals("John", response.firstName());
            assertEquals("Doe", response.lastName());
            assertEquals(25, response.age());
            assertEquals("+1234567890", response.phoneNumber());
            assertEquals("john.doe@example.com", response.email());
            assertEquals(1L, response.categoryId());
            assertEquals("Professional", response.categoryType());

            // Verify repository interaction
            verify(personRepository, times(1)).save(any(Person.class));
        }

        @Test
        @DisplayName("Should pass correct Person object to repository")
        void shouldPassCorrectPersonToRepository() {
            // Arrange
            var command = new SavePersonCommand(
                    "Jane",
                    "Smith",
                    30,
                    "+9876543210",
                    "jane.smith@example.com",
                    "456 Oak Ave",
                    2L,
                    "Personal"
            );

            var category = new Category(2L, "Personal");
            var savedPerson = new Person(
                    200L,
                    "Jane",
                    "Smith",
                    30,
                    "+9876543210",
                    "jane.smith@example.com",
                    category
            );

            when(personRepository.save(any(Person.class))).thenReturn(savedPerson);

            // Act
            savePersonUseCase.execute(command);

            // Assert - Verify what was passed to repository
            verify(personRepository).save(personCaptor.capture());
            var capturedPerson = personCaptor.getValue();

            assertNull(capturedPerson.getId()); // New person should have null ID
            assertEquals("Jane", capturedPerson.getFirstName());
            assertEquals("Smith", capturedPerson.getLastName());
            assertEquals(30, capturedPerson.getAge());
            assertEquals("+9876543210", capturedPerson.getPhoneNumber());
            assertEquals("jane.smith@example.com", capturedPerson.getEmail());
            assertEquals("Personal", capturedPerson.getCategory().getType());
        }
    }

    @Nested
    @DisplayName("Execute - Validation Failures")
    class ExecuteValidationFailures {

        @Test
        @DisplayName("Should throw DomainException when age is less than 18")
        void shouldThrowExceptionWhenAgeIsInvalid() {
            // Arrange
            var command = new SavePersonCommand(
                    "Young",
                    "Person",
                    17, // Invalid age
                    "+1234567890",
                    "young@example.com",
                    "123 Main St",
                    1L,
                    "Student"
            );

            // Act & Assert
            var exception = assertThrows(DomainException.class, () -> savePersonUseCase.execute(command));
            assertTrue(exception.getMessage().contains("Age cannot be less than 18"));

            // Verify repository was never called
            verify(personRepository, never()).save(any(Person.class));
        }

        @Test
        @DisplayName("Should throw DomainException when email is empty")
        void shouldThrowExceptionWhenEmailIsEmpty() {
            // Arrange
            var command = new SavePersonCommand(
                    "John",
                    "Doe",
                    25,
                    "+1234567890",
                    "", // Empty email
                    "123 Main St",
                    1L,
                    "Professional"
            );

            // Act & Assert
            var exception = assertThrows(DomainException.class, () -> savePersonUseCase.execute(command));
            assertTrue(exception.getMessage().contains("Email cannot be null or empty"));

            verify(personRepository, never()).save(any(Person.class));
        }

        @Test
        @DisplayName("Should throw DomainException when category type is invalid")
        void shouldThrowExceptionWhenCategoryTypeIsInvalid() {
            // Arrange
            var command = new SavePersonCommand(
                    "John",
                    "Doe",
                    25,
                    "+1234567890",
                    "john@example.com",
                    "123 Main St",
                    1L,
                    "" // Empty category type
            );

            // Act & Assert
            var exception = assertThrows(DomainException.class, () -> savePersonUseCase.execute(command));
            assertTrue(exception.getMessage().contains("Type is null or empty"));

            verify(personRepository, never()).save(any(Person.class));
        }
    }

    @Nested
    @DisplayName("Execute - Repository Exceptions")
    class ExecuteRepositoryExceptions {

        @Test
        @DisplayName("Should propagate exception when repository fails")
        void shouldPropagateExceptionWhenRepositoryFails() {
            // Arrange
            var command = new SavePersonCommand(
                    "John",
                    "Doe",
                    25,
                    "+1234567890",
                    "john.doe@example.com",
                    "123 Main St",
                    1L,
                    "Professional"
            );

            when(personRepository.save(any(Person.class)))
                    .thenThrow(new RuntimeException("Database connection failed"));

            // Act & Assert
            var exception = assertThrows(RuntimeException.class, () -> savePersonUseCase.execute(command));
            assertTrue(exception.getMessage().contains("Database connection failed"));

            verify(personRepository, times(1)).save(any(Person.class));
        }
    }
}

