package com.iluwatar.semaphore;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

/** Test class */
public class FruitShoptakeBowl000e0797584553429c7Test {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/iluwatar/semaphore/FruitShop.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 84 branch to line 86
   * conditional line 86 branch to line 87
   */

  @Test
  public void comiluwatarsemaphoreFruitShoptakeBowl000e0797584553429c7() throws Throwable {

    com.iluwatar.semaphore.FruitBowl retval;
    {
      /* Arrange */
      com.iluwatar.semaphore.FruitShop param5 =
          (com.iluwatar.semaphore.FruitShop) Reflector.getInstance("com.iluwatar.semaphore.FruitShop");
      boolean[] booleanArray = { true };
      Reflector.setField(param5, "available", booleanArray);
      com.iluwatar.semaphore.Semaphore semaphore =
          (com.iluwatar.semaphore.Semaphore) Reflector.getInstance("com.iluwatar.semaphore.Semaphore");
      Reflector.setField(semaphore, "counter", 2);
      Reflector.setField(semaphore, "licenses", 2147483646);
      Reflector.setField(param5, "semaphore", semaphore);
      com.iluwatar.semaphore.FruitBowl[] fruitBowlArray = { null };
      Reflector.setField(param5, "bowls", fruitBowlArray);

      /* Act */
      retval = param5.takeBowl();
    }
    {
      /* Assert result */
      Assert.assertEquals(null, retval);
    }
  }
}
