@startuml
package com.iluwatar.serializedentity {
  class App {
    - DB_URL : String {static}
    - LOGGER : Logger {static}
    + App()
    - createDataSource() : DataSource {static}
    - createSchema(dataSource : DataSource) {static}
    - deleteSchema(dataSource : DataSource) {static}
    + main(args : String[]) {static}
  }

  class Taxonomy {
    - speciesId : int
    - domain : String
    - kingdom : String
    - phylum : String
    - classis : String
    - order : String
    - family : String
    - genus : String
    - species : String
    ~ Taxonomy(int, String, String, String, String, String, String, String, String)
  }

  class Serialization {
    - CREATE_SCHEMA_SQL : String {static}
    - DELETE_SCHEMA_SQL : String {static}
    - LOGGER : Logger {static}
    - dataSource : DataSource
    - taxonomy : Taxonomy
    ~ Serialization(taxonomy : Taxonomy, dataSource : DataSource)
    + insert()
    + read()
    + update(updateTaxonomy : Taxonomy)
    + delete()
  }
  diamond h2db
}

App --> "Initialize Taxonomy objects" Taxonomy
App --> "Initialize Serialization objects" Serialization
Taxonomy --> "Serialized by" Serialization
Taxonomy --> "Stored in database" h2db
Serialization --> "Perform CRUD operations" h2db
@enduml