server:
    port: 8081

spring:
    application:
        name: greetingservice
eureka:
  client:
      service-url.defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
        show-details: always
    web:
      exposure:
          include: health

logging:
    file:
        name: application.log

