@startuml
package com.iluwatar.halfsynchalfasync {
  class AsynchronousService {
    - service : ExecutorService
    + AsynchronousService(workQueue : BlockingQueue<Runnable>)
    + execute(task : AsyncTask<T>)
  }
  ~class ArithmeticSumTask {
    - n : long
    + ArithmeticSumTask(n : long)
    + call() : Long
    + onError(throwable : Throwable)
    + onPostCall(result : Long)
    + onPreCall()
  }
  class App {
    + App()
    - ap(i : long) : long {static}
    + main(args : String[]) {static}
  }
  interface AsyncTask<O> {
    + call() : O {abstract}
    + onError(Throwable) {abstract}
    + onPostCall(O) {abstract}
    + onPreCall() {abstract}
  }
}
ArithmeticSumTask ..+ App
ArithmeticSumTask ..|> AsyncTask 
@enduml