@startuml
package com.iluwatar.utilitylibrary.domain {
  class Message<T> {
    - messageData : MessageData<T>
    - messageHeader : MessageHeader
    + Message<T>(messageHeader : MessageHeader, messageData : MessageData<T>)
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getMessageData() : MessageData<T>
    + getMessageHeader() : MessageHeader
    + hashCode() : int
    + setMessageData(messageData : MessageData<T>)
    + setMessageHeader(messageHeader : MessageHeader)
    + toString() : String
  }
  class MessageData<T> {
    - data : T
    + MessageData<T>(data : T)
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getData() : T
    + hashCode() : int
    + setData(data : T)
    + toString() : String
  }
  class MessageHeader {
    - dataFileName : String
    - dataLocation : String
    - operataionName : String
    + MessageHeader()
    # canEqual(other : Object) : boolean
    + equals(o : Object) : boolean
    + getDataFileName() : String
    + getDataLocation() : String
    + getOperataionName() : String
    + hashCode() : int
    + setDataFileName(dataFileName : String)
    + setDataLocation(dataLocation : String)
    + setOperataionName(operataionName : String)
    + toString() : String
  }
}
package com.iluwatar.utilitylibrary.implementation {
  class PersistentLocalStorageUtility<T> {
    - LOGGER : Logger {static}
    + PersistentLocalStorageUtility<T>()
    + dropMessageToPersistentStorage(message : Message<T>)
    + readMessageFromPersistentStorage(messageHeader : MessageHeader) : Message<T>
  }
}
package com.iluwatar.utilitylibrary.interfaces {
  interface IPersistentCommonStorageUtility<T> {
    + dropMessageToPersistentStorage(Message<T>) {abstract}
    + readMessageFromPersistentStorage(MessageHeader) : Message<T> {abstract}
  }
}
Message -->  "-messageHeader" MessageHeader
Message -->  "-messageData" MessageData
PersistentLocalStorageUtility ..|> IPersistentCommonStorageUtility 
@enduml