@startuml
package domainapp.dom.app.homepage {
  class HomePageViewModel {
    ~ simpleObjects : SimpleObjects
    + HomePageViewModel()
    + getObjects() : List<SimpleObject>
    + title() : String
  }
  class HomePageService {
    ~ container : DomainObjectContainer
    + HomePageService()
    + homePage() : HomePageViewModel
  }
}
package domainapp.dom.modules.simple {
  class SimpleObjects {
    ~ container : DomainObjectContainer
    + SimpleObjects()
    + create(name : String) : SimpleObject
    + findByName(name : String) : List<SimpleObject>
    + listAll() : List<SimpleObject>
    + title() : TranslatableString
  }
  class SimpleObject {
    - container : DomainObjectContainer
    - name : String
    + SimpleObject()
    + compareTo(other : SimpleObject) : int
    + default0UpdateName() : String
    + getName() : String
    + getVersionSequence() : Long
    + setName(name : String)
    + title() : TranslatableString
    + updateName(name : String) : SimpleObject
    + validateUpdateName(name : String) : TranslatableString
  }
}
HomePageViewModel -->  "-simpleObjects" SimpleObjects
@enduml