@startuml
package com.iluwatar.unitofwork {
  class App {
    + App()
    + main(args : String[]) {static}
  }
  interface IUnitOfWork<T> {
    + DELETE : String {static}
    + INSERT : String {static}
    + MODIFY : String {static}
    + commit() {abstract}
    + registerDeleted(T) {abstract}
    + registerModified(T) {abstract}
    + registerNew(T) {abstract}
  }
  class domain.Student {
    - address : String
    - id : Integer
    - name : String
    + domain.Student(id : Integer, name : String, address : String)
    + getAddress() : String
    + getId() : Integer
    + getName() : String
  }
  class StudentDatabase {
    + StudentDatabase()
    + delete(student : domain.Student)
    + insert(student : domain.Student)
    + modify(student : domain.Student)
  }
  class StudentRepository {
    - LOGGER : Logger {static}
    - context : Map<String, List<domain.Student>>
    - studentDatabase : StudentDatabase
    + StudentRepository(context : Map<String, List<domain.Student>>, studentDatabase : StudentDatabase)
    + commit()
    - commitDelete()
    - commitInsert()
    - commitModify()
    - register(student : domain.Student, operation : String)
    + registerDeleted(student : domain.Student)
    + registerModified(student : domain.Student)
    + registerNew(student : domain.Student)
  }
}
StudentRepository -->  "-studentDatabase" StudentDatabase
StudentRepository ..|> IUnitOfWork 
@enduml
