@startuml
package com.iluwatar.execute.around {
  interface FileWriterAction {
    + writeFile(FileWriter) {abstract}
  }
  class SimpleFileWriter {
    + SimpleFileWriter(filename : String, action : FileWriterAction)
  }
  class App {
    + App()
    + main(args : String[]) {static}
  }
}
@enduml