@startuml
package com.iluwatar.inventory.microservice {
  class InventoryController {
    + InventoryController()
    + getProductInventories() : int
  }
  class InventoryApplication {
    + InventoryApplication()
    + main(args : String[]) {static}
  }
}
@enduml