name: 'Comment on stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity.'
          close-issue-message: 'This issue was closed because it has been stalled for too long with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for too long with no activity.'
          days-before-issue-stale: 60
          days-before-pr-stale: 60
          days-before-issue-close: -1
          days-before-pr-close: -1
          exempt-issue-labels: 'info: help wanted'
